version: "3.9"

services:
  cadena:
    image: ghcr.io/matth23-sys/cadena-app:1.0.5
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.cadena.entrypoints=http"
        - "traefik.http.routers.cadena.rule=Host(`tu-dominio.com`)"
        - "traefik.http.middlewares.cadena-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.cadena.middlewares=cadena-https-redirect"
        - "traefik.http.routers.cadena-secure.entrypoints=https"
        - "traefik.http.routers.cadena-secure.rule=Host(`tu-dominio.com`)"
        - "traefik.http.routers.cadena-secure.tls=true"
        - "traefik.http.routers.cadena-secure.tls.certresolver=http"
        - "traefik.http.routers.cadena-secure.service=cadena"
        - "traefik.http.services.cadena.loadbalancer.server.port=1002"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
