name: cadena application

on:
  push:
    branches: 
      - cadena

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 1. Obtener el código del repo
    - uses: actions/checkout@v4

    # 2. Instalar Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    # 3. Instalar dependencias
    - name: Install dependencies
      run: pip install -r requirements.txt

    # 4. Login a GHCR usando tu GITHUB_TOKEN
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR }}

    # 5. Build + Push Imagen Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/matth23-sys/cadena-app:1.0.5

    # 6. DEBUG: Ver si los SECRETS existen
    - name: Debug secrets
      run: |
        echo "HOST='${{ secrets.VPS_HOST }}'"
        echo "USER='${{ secrets.VPS_USER }}'"
        echo "PORT='${{ secrets.VPS_SSH_PORT }}'"

    # 7. Probar conexión TCP al puerto 1002
    - name: Test SSH port
      run: |
        echo "Testing SSH port..."
        nc -zv ${{ secrets.VPS_HOST }} ${{ secrets.VPS_SSH_PORT }} || echo "SSH PORT NOT OPEN"

    # 8. Probar autenticación SSH
    - name: SSH Connected OK?
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          echo "SSH OK"
          hostname
          whoami
          uptime

    # 9. Copiar stack.yml al VPS
    - name: Copy stack.yml to VPS
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        port: ${{ secrets.VPS_SSH_PORT }}
        source: "stack.yml"
        target: "/home/${{ secrets.VPS_USER }}/cadena"

    # 10. Despliegue Swarm Automático
    - name: Deploy stack
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASS }}
        port: ${{ secrets.VPS_SSH_PORT }}
        script: |
          echo "Desplegando stack..."
          cd ~/cadena
          
          echo "PULL DE LA IMAGEN"
          docker login ghcr.io -u matth23-sys -p ${{ secrets.GHCR }}
          docker pull ghcr.io/matth23-sys/cadena-app:1.0.5

          echo "BAJANDO SERVICIO ANTERIOR"
          docker stack rm cadena || true

          echo "ESPERANDO 20s..."
          sleep 20

          echo "DESPLEGANDO NUEVO STACK"
          docker stack deploy --with-registry-auth -c stack.yml cadena

          echo "SERVICIOS ACTIVOS:"
          docker service ls
